util/assetbuilder: Upgrade to Node.js 4.x and node-sass@3.3.3
This is a minimal updgrade to fix the build which was failing with:

```
/app/node_modules/node-sass/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
```

Signed-off-by: Lewis Marshall <lewis@lmars.net>